package controle_acesso_new;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import acesso.Acesso;
import acesso.Acesso_Home;
import controle_acesso.Controle_Acesso_Home;
import estabelecimento.Estabelecimento;
import estabelecimento.Estabelecimento_Home;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import usuario_0.Usuario;
import usuario_0.Usuario_Home;
import utilidades.Alterar_Propriedades;
import utilidades.JOPM;

/**
 *
 * @author pc
 */
public class Controle_Acesso_New extends javax.swing.JPanel {
    
    public String icone_do_estabelecimento = "";
    
    public Controle_Acesso_Home              Controle_Acesso_Home;
    public Controle_Acesso_New_Inicio Inicio;
    
    public Usuario Usuario = new Usuario();
    public int IDUSUARIORECEBIDO = -1;
    
    public Acesso Acesso = new Acesso();
    public int IDACESSORECEBIDO = -1;
    
    public Estabelecimento Estabelecimento = new Estabelecimento();

    /**
     * Creates new form Fornecedor_New
     * @param Estabelecimento_Home2
     */
    public Controle_Acesso_New(Controle_Acesso_Home Estabelecimento_Home2) {
        initComponents();
        
        Controle_Acesso_Home       = Estabelecimento_Home2;
        Inicio = new Controle_Acesso_New_Inicio( this );
        
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public controle_acesso.Controleacesso Controleacesso;
    public Controle_Acesso_New(Controle_Acesso_Home Estabelecimento_Home2, controle_acesso.Controleacesso Controleacesso2 ) {
        initComponents();
        
        Controle_Acesso_Home  = Estabelecimento_Home2;
        
        Controleacesso = Controleacesso2;
        
        Inicio = new Controle_Acesso_New_Inicio( this, Controleacesso2 );
        
    }
    ///////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jpPermitirAcesso = new javax.swing.JPanel();
        tfUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfComando = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfComando1 = new javax.swing.JTextField();
        tfComando2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jpPermitirAcesso18 = new javax.swing.JPanel();
        tfCadastrado_Por = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        tfData_Cadastro = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jpPermitirAcesso1 = new javax.swing.JPanel();
        tfEstabelecimento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfComando5 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Controle de Acesso");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        tfUsuario.setEditable(false);
        tfUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tfUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfUsuarioMouseExited(evt);
            }
        });
        tfUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfUsuarioKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Usuário");

        tfComando.setEditable(false);
        tfComando.setBackground(new java.awt.Color(255, 255, 255));
        tfComando.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfComando.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfComando.setPreferredSize(new java.awt.Dimension(247, 23));
        tfComando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfComandoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfComandoMouseExited(evt);
            }
        });
        tfComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfComandoKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Comando");

        tfComando1.setEditable(false);
        tfComando1.setBackground(new java.awt.Color(255, 0, 51));
        tfComando1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tfComando1.setForeground(new java.awt.Color(255, 255, 255));
        tfComando1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfComando1.setText("SELECIONAR");
        tfComando1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfComando1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfComando1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfComando1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfComando1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfComando1MousePressed(evt);
            }
        });
        tfComando1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfComando1KeyReleased(evt);
            }
        });

        tfComando2.setEditable(false);
        tfComando2.setBackground(new java.awt.Color(255, 0, 51));
        tfComando2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tfComando2.setForeground(new java.awt.Color(255, 255, 255));
        tfComando2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfComando2.setText("SELECIONAR");
        tfComando2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfComando2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfComando2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfComando2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfComando2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfComando2MousePressed(evt);
            }
        });
        tfComando2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfComando2KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/cadeadoabe16x16.png"))); // NOI18N

        javax.swing.GroupLayout jpPermitirAcessoLayout = new javax.swing.GroupLayout(jpPermitirAcesso);
        jpPermitirAcesso.setLayout(jpPermitirAcessoLayout);
        jpPermitirAcessoLayout.setHorizontalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(tfUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(tfComando1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(tfComando, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(tfComando2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpPermitirAcessoLayout.setVerticalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfComando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfComando1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfComando2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(2, 2, 2)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tfCadastrado_Por.setEditable(false);
        tfCadastrado_Por.setBackground(new java.awt.Color(255, 255, 255));
        tfCadastrado_Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCadastrado_Por.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCadastrado_Por.setPreferredSize(new java.awt.Dimension(247, 23));
        tfCadastrado_Por.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCadastrado_PorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCadastrado_PorMouseExited(evt);
            }
        });
        tfCadastrado_Por.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCadastrado_PorKeyReleased(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setText("Cadastrado Por");

        tfData_Cadastro.setEditable(false);
        tfData_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        tfData_Cadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfData_Cadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfData_Cadastro.setPreferredSize(new java.awt.Dimension(185, 23));
        tfData_Cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfData_CadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfData_CadastroMouseExited(evt);
            }
        });
        tfData_Cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfData_CadastroKeyReleased(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel53.setText("Data Cadastro");

        javax.swing.GroupLayout jpPermitirAcesso18Layout = new javax.swing.GroupLayout(jpPermitirAcesso18);
        jpPermitirAcesso18.setLayout(jpPermitirAcesso18Layout);
        jpPermitirAcesso18Layout.setHorizontalGroup(
            jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso18Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCadastrado_Por, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfData_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpPermitirAcesso18Layout.setVerticalGroup(
            jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso18Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcesso18Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(2, 2, 2)
                        .addComponent(tfData_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcesso18Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(2, 2, 2)
                        .addComponent(tfCadastrado_Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tfEstabelecimento.setEditable(false);
        tfEstabelecimento.setBackground(new java.awt.Color(255, 255, 255));
        tfEstabelecimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfEstabelecimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfEstabelecimento.setPreferredSize(new java.awt.Dimension(247, 23));
        tfEstabelecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfEstabelecimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfEstabelecimentoMouseExited(evt);
            }
        });
        tfEstabelecimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEstabelecimentoKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Estabelecimento");

        tfComando5.setEditable(false);
        tfComando5.setBackground(new java.awt.Color(255, 0, 51));
        tfComando5.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        tfComando5.setForeground(new java.awt.Color(255, 255, 255));
        tfComando5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfComando5.setText("SELECIONAR");
        tfComando5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfComando5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tfComando5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfComando5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfComando5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfComando5MousePressed(evt);
            }
        });
        tfComando5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfComando5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcesso1Layout = new javax.swing.GroupLayout(jpPermitirAcesso1);
        jpPermitirAcesso1.setLayout(jpPermitirAcesso1Layout);
        jpPermitirAcesso1Layout.setHorizontalGroup(
            jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                        .addComponent(tfEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(tfComando5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpPermitirAcesso1Layout.setVerticalGroup(
            jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(2, 2, 2)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEstabelecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfComando5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jpPermitirAcesso18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpPermitirAcesso1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpPermitirAcesso18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Básicos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Inicio.salvar(new controle_acesso.Controleacesso(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUsuarioMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfUsuario, true );
    }//GEN-LAST:event_tfUsuarioMouseEntered

    private void tfUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUsuarioMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfUsuario, false );
    }//GEN-LAST:event_tfUsuarioMouseExited

    private void tfUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsuarioKeyReleased
      
    }//GEN-LAST:event_tfUsuarioKeyReleased

    private void tfComandoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComandoMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfComando, true );
    }//GEN-LAST:event_tfComandoMouseEntered

    private void tfComandoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComandoMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfComando, false );
    }//GEN-LAST:event_tfComandoMouseExited

    private void tfComandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfComandoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComandoKeyReleased

    private void tfCadastrado_PorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCadastrado_PorMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCadastrado_Por, true );    
    }//GEN-LAST:event_tfCadastrado_PorMouseEntered

    private void tfCadastrado_PorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCadastrado_PorMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCadastrado_Por, false );  
    }//GEN-LAST:event_tfCadastrado_PorMouseExited

    private void tfCadastrado_PorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCadastrado_PorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCadastrado_PorKeyReleased

    private void tfData_CadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfData_CadastroMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfData_Cadastro, true ); 
    }//GEN-LAST:event_tfData_CadastroMouseEntered

    private void tfData_CadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfData_CadastroMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfData_Cadastro, false );
    }//GEN-LAST:event_tfData_CadastroMouseExited

    private void tfData_CadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfData_CadastroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfData_CadastroKeyReleased

    private void tfComando1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando1MouseEntered

    private void tfComando1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando1MouseExited

    private void tfComando1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfComando1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando1KeyReleased

    private void tfComando2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando2MouseEntered

    private void tfComando2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando2MouseExited

    private void tfComando2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfComando2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando2KeyReleased

    private void tfComando1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando1MousePressed
        selecionarUsuario();
    }//GEN-LAST:event_tfComando1MousePressed

    private void tfComando2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando2MousePressed
        selecionarComando();
    }//GEN-LAST:event_tfComando2MousePressed

    private void tfEstabelecimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEstabelecimentoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstabelecimentoMouseEntered

    private void tfEstabelecimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEstabelecimentoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstabelecimentoMouseExited

    private void tfEstabelecimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEstabelecimentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstabelecimentoKeyReleased

    private void tfComando5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando5MouseEntered

    private void tfComando5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando5MouseExited

    private void tfComando5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComando5MousePressed
        selecionarEstabelecimento();
    }//GEN-LAST:event_tfComando5MousePressed

    private void tfComando5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfComando5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComando5KeyReleased

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpPermitirAcesso;
    private javax.swing.JPanel jpPermitirAcesso1;
    private javax.swing.JPanel jpPermitirAcesso18;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JTextField tfCadastrado_Por;
    public javax.swing.JTextField tfComando;
    public javax.swing.JTextField tfComando1;
    public javax.swing.JTextField tfComando2;
    public javax.swing.JTextField tfComando5;
    public javax.swing.JTextField tfData_Cadastro;
    public javax.swing.JTextField tfEstabelecimento;
    public javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

    Controle_Acesso_New Controle_Acesso_New_Selecionar;
    private void selecionarUsuario() {
      
        Controle_Acesso_New_Selecionar = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Usuario_Home Controle_Acesso_Home = new Usuario_Home( Controle_Acesso_New.this.Controle_Acesso_Home.Home, Controle_Acesso_New_Selecionar );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Controle_Acesso_Home, BorderLayout.CENTER  );
            
            Controle_Acesso_Home.Home.ControleTabs.AddTabSemControleNovo(Controle_Acesso_Home.tabHome, "Selecionar Usuario", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();    
    }
    
    public void setarNoJPanelUsuarioSelecionado( usuario_0.Usuario Usuario2 ) {                                                  
        try{

            Usuario = Usuario2;
            
            tfUsuario.setText( Usuario.getNomecompleto() );
            
            btSalvar.setEnabled(true);
            
            //System.out.println( "**********" + Fornecedor4.getNomeourazaosocial());
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelFornecedorSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    Controle_Acesso_New Controle_Acesso_New_Selecionar2;
    private void selecionarComando() {
      
        Controle_Acesso_New_Selecionar2 = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Acesso_Home Acesso_Home = new Acesso_Home( Controle_Acesso_New.this.Controle_Acesso_Home.Home, Controle_Acesso_New_Selecionar2 );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Acesso_Home, BorderLayout.CENTER  );
            
            Controle_Acesso_Home.Home.ControleTabs.AddTabSemControleNovo(Controle_Acesso_Home.tabHome, "Selecionar Acesso", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();    
    }
    
    public void setarNoJPanelAcessoSelecionado( acesso.Acesso Acesso2 ) {                                                  
        try{

            Acesso = Acesso2;
            
            tfComando.setText( Acesso.getComandodoacesso() );
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelFornecedorSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
    
    Controle_Acesso_New Controle_Acesso_New_SelecionarEstabelecimento;
    private void selecionarEstabelecimento() {
      
        Controle_Acesso_New_SelecionarEstabelecimento = this;
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 ); 
            
            Estabelecimento_Home Estabelecimento_Home = new Estabelecimento_Home( Controle_Acesso_New.this.Controle_Acesso_Home.Home, Controle_Acesso_New_SelecionarEstabelecimento );
            JPanel jp = new JPanel();
            jp.setLayout( new BorderLayout() );
            jp.add      ( Estabelecimento_Home, BorderLayout.CENTER  );
            
            Controle_Acesso_Home.Home.ControleTabs.AddTabSemControleNovo(Controle_Acesso_Home.tabHome, "Selecionar Estabelecimento", "/utilidades_imagens/icon.png", jp ); 
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "addAbaPesquisa(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); } } }.start();    
    }
    
    public void setarNoJPanelEstabelecimentoSelecionado( Estabelecimento estabelecimento2 ) {                                                  
        try{

            Estabelecimento = estabelecimento2;
            
            tfEstabelecimento.setText( Estabelecimento.getNomeFantasia() );
            
        } catch( Exception e ){ JOPM JOptionPaneMod = new JOPM( 2, "setarNoJPanelFornecedorSelecionado(), \n"
                + e.getMessage() + "\n", this.getClass().getSimpleName() ); }
    }
}