package acesso_new;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import acesso.Acesso_Home;
import utilidades.Alterar_Propriedades;

/**
 *
 * @author pc
 */
public class Acesso_New extends javax.swing.JPanel {
    
    public String icone_do_estabelecimento = "";
    
    Acesso_Home              Estabelecimento_Home;
    public Acesso_New_Inicio Inicio;

    /**
     * Creates new form Fornecedor_New
     */
    public Acesso_New(Acesso_Home Estabelecimento_Home2) {
        initComponents();
        
        Estabelecimento_Home       = Estabelecimento_Home2;
        Inicio = new Acesso_New_Inicio( this );
        
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public acesso.Acesso Estabelecimento;
    public Acesso_New(Acesso_Home Estabelecimento_Home2, acesso.Acesso Estabelecimento2 ) {
        initComponents();
        
        Estabelecimento_Home  = Estabelecimento_Home2;
        
        Estabelecimento = Estabelecimento2;
        
        Inicio = new Acesso_New_Inicio( this, Estabelecimento2 );
        
    }
    ///////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jpPermitirAcesso = new javax.swing.JPanel();
        tfComando = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jpPermitirAcesso18 = new javax.swing.JPanel();
        tfCadastrado_Por = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        tfData_Cadastro = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Acesso");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        tfComando.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfComando.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfComando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfComandoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfComandoMouseExited(evt);
            }
        });
        tfComando.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfComandoKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Comando");

        tfDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfDescricao.setPreferredSize(new java.awt.Dimension(247, 23));
        tfDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfDescricaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfDescricaoMouseExited(evt);
            }
        });
        tfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDescricaoKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Descrição");

        javax.swing.GroupLayout jpPermitirAcessoLayout = new javax.swing.GroupLayout(jpPermitirAcesso);
        jpPermitirAcesso.setLayout(jpPermitirAcessoLayout);
        jpPermitirAcessoLayout.setHorizontalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfComando)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPermitirAcessoLayout.setVerticalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(tfComando, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tfCadastrado_Por.setEditable(false);
        tfCadastrado_Por.setBackground(new java.awt.Color(255, 255, 255));
        tfCadastrado_Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCadastrado_Por.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCadastrado_Por.setPreferredSize(new java.awt.Dimension(247, 23));
        tfCadastrado_Por.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCadastrado_PorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCadastrado_PorMouseExited(evt);
            }
        });
        tfCadastrado_Por.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCadastrado_PorKeyReleased(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setText("Cadastrado Por");

        tfData_Cadastro.setEditable(false);
        tfData_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        tfData_Cadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfData_Cadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfData_Cadastro.setPreferredSize(new java.awt.Dimension(185, 23));
        tfData_Cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfData_CadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfData_CadastroMouseExited(evt);
            }
        });
        tfData_Cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfData_CadastroKeyReleased(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel53.setText("Data Cadastro");

        javax.swing.GroupLayout jpPermitirAcesso18Layout = new javax.swing.GroupLayout(jpPermitirAcesso18);
        jpPermitirAcesso18.setLayout(jpPermitirAcesso18Layout);
        jpPermitirAcesso18Layout.setHorizontalGroup(
            jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso18Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCadastrado_Por, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfData_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpPermitirAcesso18Layout.setVerticalGroup(
            jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso18Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcesso18Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(2, 2, 2)
                        .addComponent(tfData_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcesso18Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(2, 2, 2)
                        .addComponent(tfCadastrado_Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jpPermitirAcesso18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jpPermitirAcesso18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Básicos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Inicio.salvar(new acesso.Acesso(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfComandoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComandoMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfComando, true );
    }//GEN-LAST:event_tfComandoMouseEntered

    private void tfComandoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfComandoMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfComando, false );
    }//GEN-LAST:event_tfComandoMouseExited

    private void tfComandoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfComandoKeyReleased
      
    }//GEN-LAST:event_tfComandoKeyReleased

    private void tfDescricaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDescricaoMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfDescricao, true );
    }//GEN-LAST:event_tfDescricaoMouseEntered

    private void tfDescricaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDescricaoMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfDescricao, false );
    }//GEN-LAST:event_tfDescricaoMouseExited

    private void tfDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescricaoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDescricaoKeyReleased

    private void tfCadastrado_PorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCadastrado_PorMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCadastrado_Por, true );    
    }//GEN-LAST:event_tfCadastrado_PorMouseEntered

    private void tfCadastrado_PorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCadastrado_PorMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCadastrado_Por, false );  
    }//GEN-LAST:event_tfCadastrado_PorMouseExited

    private void tfCadastrado_PorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCadastrado_PorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCadastrado_PorKeyReleased

    private void tfData_CadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfData_CadastroMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfData_Cadastro, true ); 
    }//GEN-LAST:event_tfData_CadastroMouseEntered

    private void tfData_CadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfData_CadastroMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfData_Cadastro, false );
    }//GEN-LAST:event_tfData_CadastroMouseExited

    private void tfData_CadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfData_CadastroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfData_CadastroKeyReleased

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpPermitirAcesso;
    private javax.swing.JPanel jpPermitirAcesso18;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JTextField tfCadastrado_Por;
    public javax.swing.JTextField tfComando;
    public javax.swing.JTextField tfData_Cadastro;
    public javax.swing.JTextField tfDescricao;
    // End of variables declaration//GEN-END:variables

}