/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema_submenus;

import estabelecimento.Estabelecimento_Home;
import home_usuario_logado.Bean_Usuario_Logado;
import sistema.Sistema_Home;
import usuario_0.Usuario_Home;
import utilidades.Administrador;
import utilidades.JOPM;

/**
 *
 * @author ana
 */
public class Cadastros extends javax.swing.JPanel {

    Sistema_Home Sistema_Home;
        
    public Cadastros( Sistema_Home Sistema_Home2 ) {
        Sistema_Home = Sistema_Home2;
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btExercicios4 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btExercicios3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jToolBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(658, 71));

        jSeparator7.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator7);

        btExercicios4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/cliente.png"))); // NOI18N
        btExercicios4.setText("Usuário");
        btExercicios4.setFocusable(false);
        btExercicios4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios4MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios4);

        jSeparator8.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator8);

        btExercicios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema_imagens/home.png"))); // NOI18N
        btExercicios3.setText("Estabelecimento");
        btExercicios3.setFocusable(false);
        btExercicios3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios3MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btExercicios3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios3MousePressed

        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            if( Administrador.mapaComandos.get("ACESSO_ESTABELECIMENTO") != null ) {
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Estabelecimentos", "/sistema_imagens/livroTp.gif", new Estabelecimento_Home( Sistema_Home.Home ) );                   
            }
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }
        } catch( Exception e ){ } } }.start();      
    }//GEN-LAST:event_btExercicios3MousePressed

    private void btExercicios4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios4MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            if( Administrador.mapaComandos.get("ACESSO_USUARIO") != null ) {
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Usuários", "/sistema_imagens/livroTp.gif", new Usuario_Home( Sistema_Home.Home ) );                   
            }
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }
        } catch( Exception e ){ } } }.start();        
    }//GEN-LAST:event_btExercicios4MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExercicios3;
    private javax.swing.JButton btExercicios4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
