/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema_submenus;

import acesso.Acesso_Home;
import controle_acesso.Controle_Acesso_Home;
import estabelecimento.Estabelecimento_Home;
import home_usuario_logado.Bean_Usuario_Logado;
import importar_exportar.Importar_Exportar_Home;
import sistema.Sistema_Home;
import usuario_0.Usuario_Home;
import utilidades.Administrador;
import utilidades.JOPM;

/**
 *
 * @author ana
 */
public class Configuracoes extends javax.swing.JPanel {

    Sistema_Home Sistema_Home;
        
    public Configuracoes( Sistema_Home Sistema_Home2 ) {
        Sistema_Home = Sistema_Home2;
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btExercicios5 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btExercicios6 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jToolBar2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.setPreferredSize(new java.awt.Dimension(658, 71));

        jSeparator7.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator7);

        btExercicios5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/relatoriosdevendas.png"))); // NOI18N
        btExercicios5.setText("Análise");
        btExercicios5.setFocusable(false);
        btExercicios5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios5MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios5);

        jSeparator8.setSeparatorSize(new java.awt.Dimension(12, 0));
        jToolBar2.add(jSeparator8);

        btExercicios6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/pesquisa_placa.png"))); // NOI18N
        btExercicios6.setText("Fornecedor");
        btExercicios6.setFocusable(false);
        btExercicios6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExercicios6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExercicios6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btExercicios6MousePressed(evt);
            }
        });
        jToolBar2.add(btExercicios6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btExercicios5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios5MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            //if( Administrador.mapaComandos.get("ACESSO_CEP") != null ) {
                
                //Sistema_Home.adicionarSubmenu(new Configuracoes( Sistema_Home ) ); 
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("ANÁLISE", "/sistema_imagens/livroTp.gif", new Importar_Exportar_Home( Sistema_Home.Home ) );                   
            /*}
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }*/
        } catch( Exception e ){ } } }.start();
        /*new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            if( Administrador.mapaComandos.get("ACESSO_ACESSO") != null ) {
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Acesso", "/sistema_imagens/livroTp.gif", new Acesso_Home( Sistema_Home.Home ) );                   
            }
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }
        } catch( Exception e ){ } } }.start();*/  
    }//GEN-LAST:event_btExercicios5MousePressed

    private void btExercicios6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExercicios6MousePressed
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            //if( Administrador.mapaComandos.get("ACESSO_CEP") != null ) {
                
                //Sistema_Home.adicionarSubmenu(new Configuracoes( Sistema_Home ) ); 
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("FORNECEDORES", "/sistema_imagens/livroTp.gif", new fornecedor.Fornecedor_Home( Sistema_Home.Home ) );                   
            /*}
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }*/
        } catch( Exception e ){ } } }.start();
        /*new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            
            if( Administrador.mapaComandos.get("ACESSO_CONTROLE_ACESSO") != null ) {
                
                Sistema_Home.Home.ControleTabs.AddTabsAoHome("Controle Acesso", "/sistema_imagens/livroTp.gif", new Controle_Acesso_Home( Sistema_Home.Home ) );                   
            }
            else{ JOPM JOptionPaneMod = new JOPM( 2, "USUÁRIO SEM AUTORIZAÇÂO, "
                    + "\nO USUÁRIO LOGADO NÃO TEM PERMISSÃO PARA REALIZAR ESTA AÇÃO"
                    + "\nUSUÁRIO LOGADO: " + Bean_Usuario_Logado.NOMECOMPLETO
                    + "\nSOLICITE AUTORIZAÇÃO AO ADMINISTRADOR"
                    + "\n", "USUÁRIO SEM AUTORIZAÇÂO" );
            }
        } catch( Exception e ){ } } }.start();*/
    }//GEN-LAST:event_btExercicios6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExercicios5;
    private javax.swing.JButton btExercicios6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
