package municipio_new2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import municipio.Municipio_Home;
import java.io.File;
import utilidades.Alterar_Propriedades;

/**
 *
 * @author pc
 */
public class Municipio_New extends javax.swing.JPanel {
    
    public String icone_do_estabelecimento = "";
    
    Municipio_Home              Municipio_Home;
    public Municipio_New_Inicio Inicio;
    
    /**
     * Creates new form Fornecedor_New
     * @param Estabelecimento_Home2
     */
    public Municipio_New(Municipio_Home Estabelecimento_Home2) {
        initComponents();
        
        Municipio_Home       = Estabelecimento_Home2;
        Inicio = new Municipio_New_Inicio( this );
        
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public municipio.Municipio Municipio;
    public Municipio_New(Municipio_Home Municipio_Home2, municipio.Municipio Municipio2 ) {
        initComponents();
        
        Municipio_Home  = Municipio_Home2;
        
        Municipio = Municipio2;
        
        Inicio = new Municipio_New_Inicio( this, Municipio2 );
        
    }
    ///////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jpPermitirAcesso1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbUf = new javax.swing.JComboBox();
        jpPermitirAcesso = new javax.swing.JPanel();
        tfNome_PTBR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfCodigoIBGE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jpPermitirAcesso18 = new javax.swing.JPanel();
        tfCadastrado_Por = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        tfData_Cadastro = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jpPermitirAcesso2 = new javax.swing.JPanel();
        tfCodigoReceitaFederal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfCodigoEstadual = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Estado");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Pais");

        cbPais.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbPais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbPais.setPreferredSize(new java.awt.Dimension(212, 23));
        cbPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbPaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbPaisMouseExited(evt);
            }
        });
        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("UF");

        cbUf.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbUf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        cbUf.setPreferredSize(new java.awt.Dimension(212, 23));
        cbUf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbUfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbUfMouseExited(evt);
            }
        });
        cbUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcesso1Layout = new javax.swing.GroupLayout(jpPermitirAcesso1);
        jpPermitirAcesso1.setLayout(jpPermitirAcesso1Layout);
        jpPermitirAcesso1Layout.setHorizontalGroup(
            jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPais, 0, 261, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbUf, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPermitirAcesso1Layout.setVerticalGroup(
            jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpPermitirAcesso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(cbUf, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                    .addGroup(jpPermitirAcesso1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addComponent(cbPais, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tfNome_PTBR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNome_PTBR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNome_PTBR.setPreferredSize(new java.awt.Dimension(247, 23));
        tfNome_PTBR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNome_PTBRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNome_PTBRMouseExited(evt);
            }
        });
        tfNome_PTBR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNome_PTBRKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Nome ");

        tfCodigoIBGE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCodigoIBGE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCodigoIBGE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCodigoIBGEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCodigoIBGEMouseExited(evt);
            }
        });
        tfCodigoIBGE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoIBGEKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Código IBGE");

        javax.swing.GroupLayout jpPermitirAcessoLayout = new javax.swing.GroupLayout(jpPermitirAcesso);
        jpPermitirAcesso.setLayout(jpPermitirAcessoLayout);
        jpPermitirAcessoLayout.setHorizontalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNome_PTBR, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodigoIBGE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPermitirAcessoLayout.setVerticalGroup(
            jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcessoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(tfCodigoIBGE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcessoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(tfNome_PTBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        tfCadastrado_Por.setEditable(false);
        tfCadastrado_Por.setBackground(new java.awt.Color(255, 255, 255));
        tfCadastrado_Por.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCadastrado_Por.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCadastrado_Por.setPreferredSize(new java.awt.Dimension(247, 23));
        tfCadastrado_Por.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCadastrado_PorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCadastrado_PorMouseExited(evt);
            }
        });
        tfCadastrado_Por.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCadastrado_PorKeyReleased(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setText("Cadastrado Por");

        tfData_Cadastro.setEditable(false);
        tfData_Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        tfData_Cadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfData_Cadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfData_Cadastro.setPreferredSize(new java.awt.Dimension(185, 23));
        tfData_Cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfData_CadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfData_CadastroMouseExited(evt);
            }
        });
        tfData_Cadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfData_CadastroKeyReleased(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel53.setText("Data Cadastro");

        javax.swing.GroupLayout jpPermitirAcesso18Layout = new javax.swing.GroupLayout(jpPermitirAcesso18);
        jpPermitirAcesso18.setLayout(jpPermitirAcesso18Layout);
        jpPermitirAcesso18Layout.setHorizontalGroup(
            jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso18Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCadastrado_Por, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfData_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpPermitirAcesso18Layout.setVerticalGroup(
            jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso18Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPermitirAcesso18Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(2, 2, 2)
                        .addComponent(tfData_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcesso18Layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addGap(2, 2, 2)
                        .addComponent(tfCadastrado_Por, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tfCodigoReceitaFederal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCodigoReceitaFederal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCodigoReceitaFederal.setPreferredSize(new java.awt.Dimension(216, 23));
        tfCodigoReceitaFederal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCodigoReceitaFederalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCodigoReceitaFederalMouseExited(evt);
            }
        });
        tfCodigoReceitaFederal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoReceitaFederalKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Código Receita Federal");

        tfCodigoEstadual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCodigoEstadual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCodigoEstadual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCodigoEstadualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCodigoEstadualMouseExited(evt);
            }
        });
        tfCodigoEstadual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodigoEstadualKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Código Estadual");

        javax.swing.GroupLayout jpPermitirAcesso2Layout = new javax.swing.GroupLayout(jpPermitirAcesso2);
        jpPermitirAcesso2.setLayout(jpPermitirAcesso2Layout);
        jpPermitirAcesso2Layout.setHorizontalGroup(
            jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCodigoReceitaFederal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCodigoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPermitirAcesso2Layout.setVerticalGroup(
            jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPermitirAcesso2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPermitirAcesso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpPermitirAcesso2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(tfCodigoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPermitirAcesso2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)
                        .addComponent(tfCodigoReceitaFederal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jpPermitirAcesso18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jpPermitirAcesso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPermitirAcesso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jpPermitirAcesso18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPermitirAcesso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Básicos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Inicio.salvar(new municipio.Municipio(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfData_CadastroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfData_CadastroKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfData_CadastroKeyReleased

    private void tfData_CadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfData_CadastroMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfData_Cadastro, false );
    }//GEN-LAST:event_tfData_CadastroMouseExited

    private void tfData_CadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfData_CadastroMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfData_Cadastro, true );
    }//GEN-LAST:event_tfData_CadastroMouseEntered

    private void tfCadastrado_PorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCadastrado_PorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCadastrado_PorKeyReleased

    private void tfCadastrado_PorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCadastrado_PorMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCadastrado_Por, false );
    }//GEN-LAST:event_tfCadastrado_PorMouseExited

    private void tfCadastrado_PorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCadastrado_PorMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCadastrado_Por, true );
    }//GEN-LAST:event_tfCadastrado_PorMouseEntered

    private void tfNome_PTBRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNome_PTBRKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNome_PTBRKeyReleased

    private void tfNome_PTBRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNome_PTBRMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfNome_PTBR, false );
    }//GEN-LAST:event_tfNome_PTBRMouseExited

    private void tfNome_PTBRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNome_PTBRMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfNome_PTBR, true );
    }//GEN-LAST:event_tfNome_PTBRMouseEntered

    private void tfCodigoIBGEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoIBGEKeyReleased
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            tfCodigoIBGE.setText("");
        }
    }//GEN-LAST:event_tfCodigoIBGEKeyReleased

    private void tfCodigoIBGEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoIBGEMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCodigoIBGE, false );
    }//GEN-LAST:event_tfCodigoIBGEMouseExited

    private void tfCodigoIBGEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoIBGEMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( tfCodigoIBGE, true );
    }//GEN-LAST:event_tfCodigoIBGEMouseEntered

    private void cbPaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPaisMouseEntered
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbPais, true );
    }//GEN-LAST:event_cbPaisMouseEntered

    private void cbPaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbPaisMouseExited
        Alterar_Propriedades A_P = new Alterar_Propriedades( cbPais, false );
    }//GEN-LAST:event_cbPaisMouseExited

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed
        try{
            
            if( cbPais.getItemCount() > 0 ) {
                
                BookInfoUf obj = (BookInfoUf) cbPais.getSelectedItem();
                
                municipio.Municipio Municipio2 = new municipio.Municipio();
                Municipio2.setIdPais( obj.ID );
                
                //System.out.println( "setarCBUf 0" );
                Inicio.setarCBUf(false, Municipio2 );                
            }
        }
        catch( Exception e ){ System.out.println( "xxxxxxxxxx" ); e.printStackTrace(); }
    }//GEN-LAST:event_cbPaisActionPerformed

    private void tfCodigoReceitaFederalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoReceitaFederalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoReceitaFederalMouseEntered

    private void tfCodigoReceitaFederalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoReceitaFederalMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoReceitaFederalMouseExited

    private void tfCodigoReceitaFederalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoReceitaFederalKeyReleased
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            tfCodigoReceitaFederal.setText("");
        }
    }//GEN-LAST:event_tfCodigoReceitaFederalKeyReleased

    private void tfCodigoEstadualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoEstadualMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoEstadualMouseEntered

    private void tfCodigoEstadualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCodigoEstadualMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoEstadualMouseExited

    private void tfCodigoEstadualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoEstadualKeyReleased
        String caracteres="0987654321.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
            tfCodigoEstadual.setText("");
        }
    }//GEN-LAST:event_tfCodigoEstadualKeyReleased

    private void cbUfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbUfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUfMouseEntered

    private void cbUfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbUfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUfMouseExited

    private void cbUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUfActionPerformed

    int quantidadeDeArquivos = 0;
    /* Cria Um Arquivo Ou Informa Outro Nome Se Existir */
    private String enderecoParaCriarArquivo( File f, String endimgs ) {
        String saida = null;
        
        try{
            saida = endimgs + "\\" +
                    f.getName();            
                    
            /* Criando A Pasta */
            File criar = new File( saida );
            /* Verificando Se A Pasta Existe */
            if ( criar.exists() ) { 
                quantidadeDeArquivos++;
                File falt = new File( endimgs + "\\" + quantidadeDeArquivos+f.getName() );
                enderecoParaCriarArquivo( falt, endimgs );
            }        
            
        } catch ( Exception e ) { } 
        
        return String.valueOf( quantidadeDeArquivos );
    }
    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btSalvar;
    public javax.swing.JComboBox cbPais;
    public javax.swing.JComboBox cbUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpPermitirAcesso;
    private javax.swing.JPanel jpPermitirAcesso1;
    private javax.swing.JPanel jpPermitirAcesso18;
    private javax.swing.JPanel jpPermitirAcesso2;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JTextField tfCadastrado_Por;
    public javax.swing.JTextField tfCodigoEstadual;
    public javax.swing.JTextField tfCodigoIBGE;
    public javax.swing.JTextField tfCodigoReceitaFederal;
    public javax.swing.JTextField tfData_Cadastro;
    public javax.swing.JTextField tfNome_PTBR;
    // End of variables declaration//GEN-END:variables
    
}