/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fornecedor_new;

import fornecedor.Fornecedor_Home;
import java.awt.Color;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import utilidades.JOPM;

/**
 *
 * @author pc
 */
public class Fornecedor_New extends javax.swing.JPanel {
    
    Fornecedor_Home              Fornecedor_Home;
    public Fornecedor_New_Inicio Inicio;

    /**
     * Creates new form Fornecedor_New
     */
    public Fornecedor_New(Fornecedor_Home Fornecedor_Home2) {
        initComponents();
        
        Fornecedor_Home       = Fornecedor_Home2;
        Inicio = new Fornecedor_New_Inicio( this );
        
        //jpPermitirAcesso2.setVisible(false);
        jLabel13.setVisible(false);
        tfCPFOuCNPJ.setVisible(false);        
    }
    
    ///////////////////////////////////////////////////////////////////////////
    public fornecedor.Fornecedor Fornecedor;
    public Fornecedor_New( Fornecedor_Home Fornecedor_Home2, fornecedor.Fornecedor Fornecedor2 ) {
        initComponents();
        
        Fornecedor_Home  = Fornecedor_Home2;
        
        Fornecedor = Fornecedor2;
        
        Inicio = new Fornecedor_New_Inicio( this, Fornecedor2 );
        
        //jpPermitirAcesso2.setVisible(false);
        jLabel13.setVisible(false);
        tfCPFOuCNPJ.setVisible(false); 
    }
    ///////////////////////////////////////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpStatus1 = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        jpPermitirAcesso3 = new javax.swing.JPanel();
        rbPessoaFisica = new javax.swing.JRadioButton();
        rbPessoaJuridica = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfCPFOuCNPJ = new javax.swing.JFormattedTextField();
        tfPrazoDeEntrega = new javax.swing.JTextField();
        tfPrazoDePagamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTelefoneSupervisor = new javax.swing.JFormattedTextField();
        tfTelefoneVendedor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNomeSupervisor = new javax.swing.JTextField();
        tfNomeVendedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEmailPromotor = new javax.swing.JTextField();
        tfGeracaoPedidosRA = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfTelefonePromotor = new javax.swing.JTextField();
        tfLeadTime = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfNomePromotor = new javax.swing.JTextField();
        tfFrequencia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        tfNomeouRazaoSocial = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfNomeFantasia = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfCd = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Dados do Fornecedor");

        jpStatus1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(201, 239, 237)));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/salvar.gif"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(91, 27));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utilidades_imagens/atualizar.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);

        javax.swing.GroupLayout jpStatus1Layout = new javax.swing.GroupLayout(jpStatus1);
        jpStatus1.setLayout(jpStatus1Layout);
        jpStatus1Layout.setHorizontalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAtualizar)
                .addContainerGap())
        );
        jpStatus1Layout.setVerticalGroup(
            jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpStatus1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpStatus1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar)))
        );

        rbPessoaFisica.setText("Pessoa Física");
        rbPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaFisicaActionPerformed(evt);
            }
        });

        rbPessoaJuridica.setSelected(true);
        rbPessoaJuridica.setText("Pessoa Jurídica");
        rbPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPermitirAcesso3Layout = new javax.swing.GroupLayout(jpPermitirAcesso3);
        jpPermitirAcesso3.setLayout(jpPermitirAcesso3Layout);
        jpPermitirAcesso3Layout.setHorizontalGroup(
            jpPermitirAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPermitirAcesso3Layout.setVerticalGroup(
            jpPermitirAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPermitirAcesso3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPermitirAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("CPF ou CNPJ");

        tfCPFOuCNPJ.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCPFOuCNPJ.setPreferredSize(new java.awt.Dimension(185, 23));
        tfCPFOuCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCPFOuCNPJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCPFOuCNPJFocusLost(evt);
            }
        });
        tfCPFOuCNPJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfCPFOuCNPJMousePressed(evt);
            }
        });
        tfCPFOuCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCPFOuCNPJActionPerformed(evt);
            }
        });
        tfCPFOuCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCPFOuCNPJKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCPFOuCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCPFOuCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tfPrazoDeEntrega.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPrazoDeEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPrazoDeEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPrazoDeEntregaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPrazoDeEntregaMouseExited(evt);
            }
        });
        tfPrazoDeEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrazoDeEntregaKeyReleased(evt);
            }
        });

        tfPrazoDePagamento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfPrazoDePagamento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfPrazoDePagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfPrazoDePagamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfPrazoDePagamentoMouseExited(evt);
            }
        });
        tfPrazoDePagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPrazoDePagamentoKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("E-mail Vendedor");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("E-mail Supervisor");

        tfTelefoneSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfTelefoneSupervisor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefoneSupervisor.setPreferredSize(new java.awt.Dimension(185, 23));
        tfTelefoneSupervisor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefoneSupervisorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefoneSupervisorFocusLost(evt);
            }
        });
        tfTelefoneSupervisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfTelefoneSupervisorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfTelefoneSupervisorMouseExited(evt);
            }
        });
        tfTelefoneSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefoneSupervisorKeyReleased(evt);
            }
        });

        tfTelefoneVendedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        try {
            tfTelefoneVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefoneVendedor.setPreferredSize(new java.awt.Dimension(185, 23));
        tfTelefoneVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTelefoneVendedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTelefoneVendedorFocusLost(evt);
            }
        });
        tfTelefoneVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfTelefoneVendedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfTelefoneVendedorMouseExited(evt);
            }
        });
        tfTelefoneVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefoneVendedorKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Telefone Vendedor");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Telefone Supervisor");

        tfNomeSupervisor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeSupervisor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeSupervisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeSupervisorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeSupervisorMouseExited(evt);
            }
        });
        tfNomeSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeSupervisorActionPerformed(evt);
            }
        });
        tfNomeSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeSupervisorKeyReleased(evt);
            }
        });

        tfNomeVendedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeVendedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeVendedor.setPreferredSize(new java.awt.Dimension(212, 22));
        tfNomeVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeVendedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeVendedorMouseExited(evt);
            }
        });
        tfNomeVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeVendedorActionPerformed(evt);
            }
        });
        tfNomeVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeVendedorKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Nome Vendedor");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Nome Supervisor");

        tfEmailPromotor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfEmailPromotor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfEmailPromotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfEmailPromotorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfEmailPromotorMouseExited(evt);
            }
        });
        tfEmailPromotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmailPromotorKeyReleased(evt);
            }
        });

        tfGeracaoPedidosRA.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfGeracaoPedidosRA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfGeracaoPedidosRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfGeracaoPedidosRAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfGeracaoPedidosRAMouseExited(evt);
            }
        });
        tfGeracaoPedidosRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfGeracaoPedidosRAKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Geração Pedidos RA");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("E-mail Promotor");

        tfTelefonePromotor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfTelefonePromotor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfTelefonePromotor.setPreferredSize(new java.awt.Dimension(212, 22));
        tfTelefonePromotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfTelefonePromotorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfTelefonePromotorMouseExited(evt);
            }
        });
        tfTelefonePromotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonePromotorActionPerformed(evt);
            }
        });
        tfTelefonePromotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTelefonePromotorKeyReleased(evt);
            }
        });

        tfLeadTime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfLeadTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfLeadTime.setPreferredSize(new java.awt.Dimension(212, 22));
        tfLeadTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfLeadTimeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfLeadTimeMouseExited(evt);
            }
        });
        tfLeadTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLeadTimeActionPerformed(evt);
            }
        });
        tfLeadTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLeadTimeKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Lead Time");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Telefone Promotor");

        tfNomePromotor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomePromotor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomePromotor.setPreferredSize(new java.awt.Dimension(212, 22));
        tfNomePromotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomePromotorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomePromotorMouseExited(evt);
            }
        });
        tfNomePromotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomePromotorActionPerformed(evt);
            }
        });
        tfNomePromotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomePromotorKeyReleased(evt);
            }
        });

        tfFrequencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfFrequencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfFrequencia.setPreferredSize(new java.awt.Dimension(212, 22));
        tfFrequencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfFrequenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfFrequenciaMouseExited(evt);
            }
        });
        tfFrequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFrequenciaActionPerformed(evt);
            }
        });
        tfFrequencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFrequenciaKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Frequência");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Nome Promotor");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Código do Fornecedor");

        tfNomeouRazaoSocial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeouRazaoSocial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeouRazaoSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeouRazaoSocialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeouRazaoSocialMouseExited(evt);
            }
        });
        tfNomeouRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeouRazaoSocialKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Nome Fantasia");

        tfNomeFantasia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfNomeFantasia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfNomeFantasia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfNomeFantasiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfNomeFantasiaMouseExited(evt);
            }
        });
        tfNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeFantasiaActionPerformed(evt);
            }
        });
        tfNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNomeFantasiaKeyReleased(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("ABASTECIMENTO");

        tfCd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tfCd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        tfCd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tfCdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfCdMouseExited(evt);
            }
        });
        tfCd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCdActionPerformed(evt);
            }
        });
        tfCd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(jpStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jpPermitirAcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfLeadTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfNomeouRazaoSocial)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfFrequencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfCd)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(tfPrazoDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tfTelefoneVendedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(tfGeracaoPedidosRA, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNomePromotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTelefonePromotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfEmailPromotor)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfPrazoDeEntrega)
                                    .addComponent(tfTelefoneSupervisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNomeSupervisor)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpStatus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPermitirAcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(2, 2, 2)
                        .addComponent(tfNomePromotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(tfTelefonePromotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(tfEmailPromotor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)
                        .addComponent(tfNomeSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(tfTelefoneSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(tfPrazoDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNomeouRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLeadTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfGeracaoPedidosRA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(tfNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(tfTelefoneVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)
                        .addComponent(tfPrazoDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfPrazoDeEntrega, tfPrazoDePagamento});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel11, jLabel12});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfFrequencia, tfNomePromotor});

    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Inicio.salvar( new fornecedor.Fornecedor(), false );
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeouRazaoSocialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeouRazaoSocialMouseEntered
        mouseEntra( tfNomeouRazaoSocial );
    }//GEN-LAST:event_tfNomeouRazaoSocialMouseEntered

    private void tfNomeouRazaoSocialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeouRazaoSocialMouseExited
        mouseSai( tfNomeouRazaoSocial );
    }//GEN-LAST:event_tfNomeouRazaoSocialMouseExited

    private void tfNomeouRazaoSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeouRazaoSocialKeyReleased

    }//GEN-LAST:event_tfNomeouRazaoSocialKeyReleased

    private void tfNomeVendedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeVendedorMouseEntered
        mouseEntra( tfNomeVendedor );
    }//GEN-LAST:event_tfNomeVendedorMouseEntered

    private void tfNomeVendedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeVendedorMouseExited
        mouseSai( tfNomeVendedor );
    }//GEN-LAST:event_tfNomeVendedorMouseExited

    private void tfNomeVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeVendedorKeyReleased

    }//GEN-LAST:event_tfNomeVendedorKeyReleased

    private void tfTelefoneVendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorFocusGained
        setarFocusGainedTelefone( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorFocusGained

    private void tfTelefoneVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorFocusLost
        setarFocusLostTelefone( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorFocusLost

    private void tfTelefoneVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorKeyReleased
     
    }//GEN-LAST:event_tfTelefoneVendedorKeyReleased

    private void tfTelefoneVendedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorMouseEntered
        mouseEntra( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorMouseEntered

    private void tfTelefoneVendedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneVendedorMouseExited
        mouseSai( tfTelefoneVendedor );
    }//GEN-LAST:event_tfTelefoneVendedorMouseExited

    private void tfNomeFantasiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeFantasiaMouseEntered
        mouseEntra( tfNomeFantasia );
    }//GEN-LAST:event_tfNomeFantasiaMouseEntered

    private void tfNomeFantasiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeFantasiaMouseExited
        mouseSai( tfNomeFantasia );
    }//GEN-LAST:event_tfNomeFantasiaMouseExited

    private void tfNomeFantasiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeFantasiaKeyReleased
   
    }//GEN-LAST:event_tfNomeFantasiaKeyReleased

    private void tfNomeSupervisorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeSupervisorMouseEntered
        mouseEntra( tfNomeSupervisor );
    }//GEN-LAST:event_tfNomeSupervisorMouseEntered

    private void tfNomeSupervisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomeSupervisorMouseExited
        mouseSai( tfNomeSupervisor );
    }//GEN-LAST:event_tfNomeSupervisorMouseExited

    private void tfNomeSupervisorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeSupervisorKeyReleased

    }//GEN-LAST:event_tfNomeSupervisorKeyReleased

    private void tfTelefoneSupervisorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorFocusGained
        setarFocusGainedTelefone( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorFocusGained

    private void tfTelefoneSupervisorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorFocusLost
        setarFocusLostTelefone( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorFocusLost

    private void tfTelefoneSupervisorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorMouseEntered
        mouseEntra( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorMouseEntered

    private void tfTelefoneSupervisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorMouseExited
        mouseSai( tfTelefoneSupervisor );
    }//GEN-LAST:event_tfTelefoneSupervisorMouseExited

    private void tfTelefoneSupervisorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefoneSupervisorKeyReleased
  
    }//GEN-LAST:event_tfTelefoneSupervisorKeyReleased

    private void tfPrazoDePagamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDePagamentoMouseEntered
        mouseEntra( tfPrazoDePagamento );
    }//GEN-LAST:event_tfPrazoDePagamentoMouseEntered

    private void tfPrazoDePagamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDePagamentoMouseExited
        mouseSai( tfPrazoDePagamento );
    }//GEN-LAST:event_tfPrazoDePagamentoMouseExited

    private void tfPrazoDePagamentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrazoDePagamentoKeyReleased
 
    }//GEN-LAST:event_tfPrazoDePagamentoKeyReleased

    private void tfPrazoDeEntregaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDeEntregaMouseEntered
        mouseEntra( tfPrazoDeEntrega );
    }//GEN-LAST:event_tfPrazoDeEntregaMouseEntered

    private void tfPrazoDeEntregaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPrazoDeEntregaMouseExited
        mouseSai( tfPrazoDeEntrega );
    }//GEN-LAST:event_tfPrazoDeEntregaMouseExited

    private void tfPrazoDeEntregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrazoDeEntregaKeyReleased
 
    }//GEN-LAST:event_tfPrazoDeEntregaKeyReleased

    private void tfCPFOuCNPJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMousePressed
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){
        }
        else{

            JOPM JOptionPaneMod = new JOPM( 2, "O Campo Pessoa Física ou Jurídica não pode ser nulo"
                + "\nEscolha um dos ítens"
                + "\nExemplo:"
                + "\n    Pessoa Física"
                + "\n    Pessoa Jurídica"
                , "Pessoa Física ou Jurídica" );
            rbPessoaFisica.requestFocus();
        }
    }//GEN-LAST:event_tfCPFOuCNPJMousePressed

    private void tfCPFOuCNPJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJFocusGained
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){

            if( rbPessoaFisica.isSelected() ){

                setarFocusGainedCPF( tfCPFOuCNPJ );
            }
            else if( rbPessoaJuridica.isSelected() ){

                setarFocusGainedCNPJ( tfCPFOuCNPJ );
            }
        }
    }//GEN-LAST:event_tfCPFOuCNPJFocusGained

    private void tfCPFOuCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJFocusLost
        if( rbPessoaJuridica.isSelected() || rbPessoaFisica.isSelected() ){

            if( rbPessoaFisica.isSelected() ){

                setarFocusLostCPF( tfCPFOuCNPJ );
            }
            else if( rbPessoaJuridica.isSelected() ){

                setarFocusLostCNPJ( tfCPFOuCNPJ );
            }
        }
    }//GEN-LAST:event_tfCPFOuCNPJFocusLost

    private void rbPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaFisicaActionPerformed
        tfCPFOuCNPJ.setValue("");
        rbPessoaJuridica.setSelected(false);
        rbPessoaFisicaMascara();
  
    }//GEN-LAST:event_rbPessoaFisicaActionPerformed

    private void rbPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaJuridicaActionPerformed
        tfCPFOuCNPJ.setValue("");
        rbPessoaFisica.setSelected(false);
        rbPessoaJuridicaMascara();
   

    }//GEN-LAST:event_rbPessoaJuridicaActionPerformed

    private void tfCPFOuCNPJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJKeyReleased
    
    }//GEN-LAST:event_tfCPFOuCNPJKeyReleased

    private void tfCPFOuCNPJMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMouseEntered
        mouseEntra( tfCPFOuCNPJ );
    }//GEN-LAST:event_tfCPFOuCNPJMouseEntered

    private void tfCPFOuCNPJMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJMouseExited
        mouseSai( tfCPFOuCNPJ );
    }//GEN-LAST:event_tfCPFOuCNPJMouseExited

    private void tfNomeSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeSupervisorActionPerformed

    private void tfCPFOuCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCPFOuCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCPFOuCNPJActionPerformed

    private void tfGeracaoPedidosRAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfGeracaoPedidosRAMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGeracaoPedidosRAMouseEntered

    private void tfGeracaoPedidosRAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfGeracaoPedidosRAMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGeracaoPedidosRAMouseExited

    private void tfGeracaoPedidosRAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGeracaoPedidosRAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGeracaoPedidosRAKeyReleased

    private void tfEmailPromotorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmailPromotorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailPromotorMouseEntered

    private void tfEmailPromotorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfEmailPromotorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailPromotorMouseExited

    private void tfEmailPromotorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailPromotorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailPromotorKeyReleased

    private void tfFrequenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFrequenciaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFrequenciaMouseEntered

    private void tfFrequenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFrequenciaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFrequenciaMouseExited

    private void tfFrequenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFrequenciaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFrequenciaKeyReleased

    private void tfNomePromotorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomePromotorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomePromotorMouseEntered

    private void tfNomePromotorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNomePromotorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomePromotorMouseExited

    private void tfNomePromotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomePromotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomePromotorActionPerformed

    private void tfNomePromotorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomePromotorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomePromotorKeyReleased

    private void tfFrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFrequenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFrequenciaActionPerformed

    private void tfNomeVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeVendedorActionPerformed

    private void tfCdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCdMouseEntered

    private void tfCdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfCdMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCdMouseExited

    private void tfCdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCdKeyReleased

    private void tfNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeFantasiaActionPerformed

    private void tfCdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCdActionPerformed

    private void tfTelefonePromotorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefonePromotorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonePromotorMouseEntered

    private void tfTelefonePromotorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfTelefonePromotorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonePromotorMouseExited

    private void tfTelefonePromotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonePromotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonePromotorActionPerformed

    private void tfTelefonePromotorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonePromotorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonePromotorKeyReleased

    private void tfLeadTimeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLeadTimeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLeadTimeMouseEntered

    private void tfLeadTimeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfLeadTimeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLeadTimeMouseExited

    private void tfLeadTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLeadTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLeadTimeActionPerformed

    private void tfLeadTimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLeadTimeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLeadTimeKeyReleased

    private void rbPessoaFisicaMascara(){                                               
        try {
                
                MaskFormatter mascara = new MaskFormatter("###.###.###-##");
                mascara.setValidCharacters("0123456789");
                
                tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            } 
    }
    
    private void rbPessoaJuridicaMascara(){                                               
        try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("##.###.###/####-##");
                mascaraTelefone.setValidCharacters("0123456789");
                
                tfCPFOuCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
    }
    
    private void setarFocusGainedCNPJ( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals(".   .   /    -") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("##.###.###/####-##");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCNPJ( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 18 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }
    
    private void setarFocusGainedCPF( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals(".   .   -") ){   
            
            try {
                
                MaskFormatter mascara = new MaskFormatter("###.###.###-##");
                mascara.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
            }
            ftm.setText( "" );            
        }                
    }
    
    public void setarFocusLostCPF( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 14 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascara = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascara ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        tfCPFOuCNPJ.requestFocus();
                }
            }
        }              
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAtualizar;
    public javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpPermitirAcesso3;
    private javax.swing.JPanel jpStatus1;
    public javax.swing.JRadioButton rbPessoaFisica;
    public javax.swing.JRadioButton rbPessoaJuridica;
    public javax.swing.JFormattedTextField tfCPFOuCNPJ;
    public javax.swing.JTextField tfCd;
    public javax.swing.JTextField tfEmailPromotor;
    public javax.swing.JTextField tfFrequencia;
    public javax.swing.JTextField tfGeracaoPedidosRA;
    public javax.swing.JTextField tfLeadTime;
    public javax.swing.JTextField tfNomeFantasia;
    public javax.swing.JTextField tfNomePromotor;
    public javax.swing.JTextField tfNomeSupervisor;
    public javax.swing.JTextField tfNomeVendedor;
    public javax.swing.JTextField tfNomeouRazaoSocial;
    public javax.swing.JTextField tfPrazoDeEntrega;
    public javax.swing.JTextField tfPrazoDePagamento;
    public javax.swing.JTextField tfTelefonePromotor;
    public javax.swing.JFormattedTextField tfTelefoneSupervisor;
    public javax.swing.JFormattedTextField tfTelefoneVendedor;
    // End of variables declaration//GEN-END:variables

    private void mouseEntra(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 204));

            c.setBackground(Color.YELLOW);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        }catch(Exception e ){}
    }
    
    private void mouseSai(javax.swing.JComponent c) {                                                  
        try{
            c.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            c.setForeground(new java.awt.Color(0, 0, 0));

            c.setBackground(Color.WHITE);
            c.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(201, 239, 237), 1, true));
        }catch(Exception e ){}
    }
    
    private void setarFocusGainedTelefone( JFormattedTextField ftm ) {
        if( ftm.getText().trim().equals("") || ftm.getText().trim().equals("+    (    )      -") ){   
            
            try {
                
                MaskFormatter mascaraTelefone = new MaskFormatter("+ ## ( ## ) #### - ####");
                mascaraTelefone.setValidCharacters("0123456789");
                
                ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );                
            } catch ( Exception e ) {
                JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        ftm.requestFocus();
            }
            ftm.setText( "5585" );            
        }                
    } 
    
    public void setarFocusLostTelefone( JFormattedTextField ftm ) {
                
        if( !ftm.getText().trim().equals("") ){  
            
            if( ftm.getText().trim().length() < 23 ){ ftm.setValue( "" );
                
                try {                    
                    MaskFormatter mascaraTelefone = new MaskFormatter(""); 
                    ftm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory( mascaraTelefone ) );
                    ftm.setText( "" ); 
                } catch ( Exception e ) {
                    JOPM JOptionPaneMod = new JOPM( 2, "Erro ao setar Máscara, "
                        +"\n" + e.toString()
                                , "Erro ao setar Máscara" );
                        ftm.requestFocus();
                }
            }
        }              
    }
    
}
